#!/bin/sh
#
# Unbind XADC
#
case "$1" in
 start)
	#echo f8007100.adc > /sys/bus/platform/drivers/xadc/unbind
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
