#!/bin/sh
#
# Start watchdog
#

case "$1" in
 start)
	echo -n "Starting watchdog: "
	watchdog -t 5 -T 10 /dev/watchdog
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
