#!/bin/sh
#
# Start the network....
#

case "$1" in
  start)
	printf "Starting network: "
	/sbin/udhcpc -n -t 7 || /sbin/ifconfig eth0 192.168.2.1 up
	;;
  stop)
	printf "Stopping network: "
	/sbin/ifconfig eth0 down
	killall -7 udhcpc
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

